package com.locations.batch.locationsbatch.enums;

import java.util.stream.Stream;

public enum AddressType {

	ADMINISTRATIVE_AREA_LEVEL_1, ADMINISTRATIVE_AREA_LEVEL_2, ADMINISTRATIVE_AREA_LEVEL_3, ADMINISTRATIVE_AREA_LEVEL_4,
	ADMINISTRATIVE_AREA_LEVEL_5, ARCHIPELAGO, COLLOQUIAL_AREA, CONTINENT, COUNTRY, ESTABLISHMENT, FINANCE, FLOOR, FOOD,
	GENERAL_CONTRACTOR, GEOCODE, HEALTH, INTERSECTION, LOCALITY, NATURAL_FEATURE, NEIGHBORHOOD, PLACE_OF_WORSHIP,
	POINT_OF_INTEREST, POLITICAL, POST_BOX, POSTAL_CODE, POSTAL_CODE_PREFIX, POSTAL_CODE_SUFFIX, POSTAL_TOWN, PREMISE,
	ROOM, ROUTE, STREET_ADDRESS, STREET_NUMBER, SUBLOCALITY, SUBLOCALITY_LEVEL_1, SUBLOCALITY_LEVEL_2,
	SUBLOCALITY_LEVEL_3, SUBLOCALITY_LEVEL_4, SUBLOCALITY_LEVEL_5, SUBPREMISE, TOWN_SQUARE, PARKING, BUS_STATION,
	TRAIN_STATION, TRANSIT_STATION, AIRPORT, PARK;

	public static AddressType resolve(String addressType) {
		return Stream.of(values()).filter(value -> addressType.toUpperCase().equals(value.name())).findFirst()
				.orElseThrow(() -> new IllegalArgumentException("The ".concat(addressType).concat(" was not found!")));
	}

}
